= link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/client/diftech/processing/papi/gateway/api/v1/gateway_service.proto[ReissueDigitalCard]

== 🗂️ Diagram

[plantuml,format="svg"]
----
@startuml
title ReissueDigitalCard
autonumber
skinparam maxmessagesize 310
participant MAPP <<CAAMobile>>
participant CAA.APIGW as APIGW <<ProcessingGatewayService>>
participant FINANCE.Cashback <<LoyaltyProgramService>>
participant CORE.CardManager as CardManager <<CardsService>>
participant CORE.Kernel <<AccountService>>
participant CORE.Ap <<LimitsService>>
participant PLATFORM.Ab_Proxy as Ab_Proxy <<AbProxyService>>
participant CAA.OperFeed as OperFeed <<OperationFeedService>>
participant ANTIFRAUD.RestrictionManager as ANTIFRAUD <<TransactionService>>

MAPP -> APIGW: ReissueDigitalCard (card_id, account_id)
APIGW -> CardManager: ListUserCards (user_id)
CardManager --> APIGW: response (cards)
alt check if ReissueDigitalCard.user_id (header) equal one of ListUserCardsResponse.userId
  APIGW --> MAPP: [If cards doesn't exist to the user] result_error
end
alt  count how many cards of this type are issued in the current month using ListUserCardsResponse.cards.activateTime
   APIGW --> MAPP: [If count > Config.value] result_error (REISSUE_DIGITAL_CARD_ERROR_TYPE_MONTHLY_LIMIT_REACHED)
end
group  define account type
  APIGW -> CORE.Kernel: GetAccountByID (account_id)
  CORE.Kernel --> APIGW: result (Account)
end
group #F3F7F3 define loyalty_program
  APIGW -> FINANCE.Cashback: GetLoyaltyProgram (client_id, loyalty_program_source=LOYALTY_PROGRAM_SOURCE_PLATA)
  FINANCE.Cashback --> APIGW: (loyalty_program_link)
end

APIGW -> Ab_Proxy: GetFeatures (user_id)
Ab_Proxy --> APIGW: response (feature_toggles)

APIGW -> CardManager: CreateVirtualCard (card_ancestor_id, account_id, audit_context, design, processor)
CardManager --> APIGW: response (card)

group #F3F7F3 common card resolving
  group limits
    APIGW -> CORE.Ap: GetCardLimitsByIds
    CORE.Ap --> APIGW: response (limits)
  end
  group #A8E1A7 card restrictions
    else if card.status = CARD_STATUS_BLOCKED and fraud_confirmed = false
      APIGW -> ANTIFRAUD: GetRestrictedTransactionsByCards(card_id)
      ANTIFRAUD --> APIGW: response (card_id, <transaction_id, user_confirmation>)
      APIGW -> OperFeed: GetFeed (integration_ids: transaction_ids)
      OperFeed --> APIGW: response (operations)
      APIGW -> APIGW: fill the card_blocked_antifraud field
  end
end

APIGW --> MAPP: response (card)

@enduml
----
== 🗂️ Requests

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/client/diftech/processing/papi/gateway/api/v1/gateway_service.proto[1.2 ReissueDigitalCardRequest]

[id='clientdiftechprocessingpapigatewayapiv1ReissueDigitalCardRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".client.diftech.processing.papi.gateway.api.v1.ReissueDigitalCardRequest"]
|===
| Request Fields | Source | Logic
| card_id
a|
----
-
----
a|
[subs="+macros"]
----
-
----
| account_id
a|
----
-
----
a|
[subs="+macros"]
----
-
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/cardmanager/v1/card_service.proto[1.3 ListUserCardsRequest]

[id='backenddiftechprocessingcorecardmanagerv1ListUserCardsRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=505,data-model=".backend.diftech.processing.core.cardmanager.v1.ListUserCardsRequest"]
|===
| Request Fields | Source | Logic
| user_id
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id)
----
a|
[subs="+macros"]
----
as is
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/kernel/v1/account_api.proto[1.4 GetAccountByIDRequest]

[id='backenddiftechprocessingcorekernelv1GetAccountByIDRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=508,data-model=".backend.diftech.processing.core.kernel.v1.GetAccountByIDRequest"]
|===
| Request Fields | Source | Logic
| account_id
a|
----
ReissueDigitalCardRequest (account_id)
----
a|
[subs="+macros"]
----
as is
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/finance/cashback/cashback/external/loyalty_program/v1/loyalty_program_service.proto[1.5 GetLoyaltyProgramRequest]

[id='backenddiftechprocessingfinancecashbackcashbackexternalloyalty_programv1GetLoyaltyProgramRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=510,data-model=".backend.diftech.processing.finance.cashback.cashback.external.loyalty_program.v1.GetLoyaltyProgramRequest"]
|===
| Request Fields | Source | Logic
| client_id
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id)
----
a|
[subs="+macros"]
----
-
----
| loyalty_program_source
a|
----
-
----
a|
[subs="+macros"]
----
const: LOYALTY_PROGRAM_SOURCE_PLATA
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/platform/ab_proxy/v1/ab_proxy.proto[1.6 GetFeaturesRequest]

[id='backenddiftechplatformab_proxyv1GetFeaturesRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=512,data-model=".backend.diftech.platform.ab_proxy.v1.GetFeaturesRequest"]
|===
| Request Fields | Source | Logic
| id
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id)
----
a|
[subs="+macros"]
----
xref:backenddiftechplatformab_proxyv1FeatureId[FeatureId]
----
| channel
a|
----
-
----
a|
[subs="+macros"]
----
const = GET_FEATURES_CHANNEL_BACK
----
| project_ids
a|
----
-
----
a|
[subs="+macros"]
----
const = CAA_BACKEND
----
| extra_params
a|
----

----
a|
[subs="+macros"]
----
xref:googleprotobufStruct[Struct]
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/platform/ab_proxy/v1/ab_proxy.proto[1.6.1 FeatureId]

[id='backenddiftechplatformab_proxyv1FeatureId']
[cols="15%,30%,55%",options="header",data-dependency-id=512,data-model=".backend.diftech.platform.ab_proxy.v1.FeatureId"]
|===
| Request Fields | Source | Logic
| email
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| user_id
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id)
----
a|
[subs="+macros"]
----
xref:commondiftechtypesstdv1UUID[UUID]
as is
----
| person_id
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| employee_id
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| identity_id
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechtypesstdv1UUID[UUID]
don't set
----
| phone_number
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| user_id_hash
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/uuid.proto[1.6.2 UUID]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/google/protobuf/struct.proto[1.6.3 Struct]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/google/protobuf/struct.proto[1.6.4 FieldsEntry]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/google/protobuf/struct.proto[1.6.5 Value]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/google/protobuf/struct.proto[1.6.6 ListValue]

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/cardmanager/v1/card_service.proto[1.7 CreateVirtualCardRequest]

[id='backenddiftechprocessingcorecardmanagerv1CreateVirtualCardRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=514,data-model=".backend.diftech.processing.core.cardmanager.v1.CreateVirtualCardRequest"]
|===
| Request Fields | Source | Logic
| design
a|
----
GetAccountByIDResponse
(account_type),
GetLoyaltyProgramResponse
(.loyalty_program_link .loyalty_program)
----
a|
[subs="+macros"]
----
IF account_type == CREDIT_CARD
    AND loyalty_program IN (CASHBACK, UNSPECIFIED)
→ design = CARD_DESIGN_CREDITO

IF account_type == DEBIT_CARD
   AND loyalty_program IN (CASHBACK, UNSPECIFIED)
→ design = CARD_DESIGN_CUENTA

IF account_type == CREDIT_CARD
   AND loyalty_program == VIAJES
→ design = CARD_DESIGN_VIAJES

IF account_type == DEBIT_CARD
   AND loyalty_program == VIAJES
→ ERROR: unsupported combination
----
| processor
a|
----
feature_toggles(caa_virtual_card_creation_phoenix)
----
a|
[subs="+macros"]
----
We start to migrate to new processing Phoenix and want to try create part of the new cards on it

If feature_toggle = caa_virtual_card_creation_phoenix = false →
don’t set processor

If feature_toggle = caa_virtual_card_creation_phoenix = true →
processor = PROCESSOR_PHOENIX
----
| account_id
a|
----
ReissueDigitalCardRequest (account_id)
----
a|
[subs="+macros"]
----
-
----
| program_id
a|
----
-
----
a|
[subs="+macros"]
----
  // Identifier of the program to which the card will be assigned.
  // If not provided, the default program will be used.
----
| audit_context
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id, header.x-plata-device-id)
----
a|
[subs="+macros"]
----
xref:backenddiftechprocessingcorecardmanagerv1AuditContext[AuditContext]
----
| idempotency_key
a|
----
ReissueDigitalCardRequest (header.idempotency-Key)
----
a|
[subs="+macros"]
----
We shall use header.Idempotency-Key as value for the parameter. If there is no Idempotency-Key header we need to calculate it with random UUID.
----
| card_ancestor_id
a|
----
ReissueDigitalCardRequest (card_id)
----
a|
[subs="+macros"]
----
if sent card_ancestor_id in this request then it means CM will closed the card and create new one, otherwise will be just new created
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/cardmanager/v1/audit.proto[1.7.1 AuditContext]

[id='backenddiftechprocessingcorecardmanagerv1AuditContext']
[cols="15%,30%,55%",options="header",data-dependency-id=514,data-model=".backend.diftech.processing.core.cardmanager.v1.AuditContext"]
|===
| Request Fields | Source | Logic
| initiator_system
a|
----
-
----
a|
[subs="+macros"]
----
const: SYSTEM_PROCESSING_PAPI

----
| initiator_details
a|
----
ReissueDigitalCardRequest (header.x-plata-user-id, header.x-plata-device-id)
----
a|
[subs="+macros"]
----
xref:backenddiftechprocessingcorecardmanagerv1AuditContextInitiatorDetailsEntry[InitiatorDetailsEntry]
{
key = user_id
value = x_plata_user_id
},

{
key = device-id
value = x-plata-device-id
}
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/cardmanager/v1/audit.proto[1.7.2 InitiatorDetailsEntry]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/uuid.proto[1.7.3 UUID]

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/core/ap/v1/limits_service.proto[1.8 GetCardLimitsByIdsRequest]

[id='backenddiftechprocessingcoreapv1GetCardLimitsByIdsRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=515,data-model=".backend.diftech.processing.core.ap.v1.GetCardLimitsByIdsRequest"]
|===
| Request Fields | Source | Logic
| ids
a|
----
CreateVirtualCardResponse (card.id)
----
a|
[subs="+macros"]
----
as is
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/antifraud/restrictionmanager/v1/transaction_service.proto[1.9 GetRestrictedTransactionsByCardsRequest]

[id='backenddiftechprocessingantifraudrestrictionmanagerv1GetRestrictedTransactionsByCardsRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=517,data-model=".backend.diftech.processing.antifraud.restrictionmanager.v1.GetRestrictedTransactionsByCardsRequest"]
|===
| Request Fields | Source | Logic
| cards
a|
----
CreateVirtualCardResponse (card.id)
----
a|
[subs="+macros"]
----
as is
----
|===

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/papi/operfeed/v2/rpc_get_feed.proto[1.10 GetFeedRequest]

[id='backenddiftechprocessingpapioperfeedv2GetFeedRequest']
[cols="15%,30%,55%",options="header",data-dependency-id=519,data-model=".backend.diftech.processing.papi.operfeed.v2.GetFeedRequest"]
|===
| Request Fields | Source | Logic
| user_id
a|
----
ReissureDigitalCardRequest (header.x-plata-user-id)
----
a|
[subs="+macros"]
----
as is
----
| card_ids
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| brand_ids
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| pagination
a|
----
-
----
a|
[subs="+macros"]
----
xref:backenddiftechprocessingpapioperfeedtypesv2PaginationFilter[PaginationFilter]
----
| account_ids
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| user_groups
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| category_keys
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| integration_ids
a|
----
GetRestrictedTransactionsByCardsResponse (cards.transaction_id)
----
a|
[subs="+macros"]
----
as is
----
| operation_types
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| operation_filter
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
| invest_instrument_ids
a|
----
-
----
a|
[subs="+macros"]
----
don't set
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/backend/diftech/processing/papi/operfeed/types/v2/pagination_filter.proto[1.10.1 PaginationFilter]

[id='backenddiftechprocessingpapioperfeedtypesv2PaginationFilter']

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/datetime.proto[1.10.2 DateTime]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/duration.proto[1.10.3 Duration]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/datetime.proto[1.10.4 TimeZone]

== 🗂️ Response

== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/client/diftech/processing/papi/gateway/api/cards/v1/reissue_digital_card.proto[2.1 ReissueDigitalCardResponse]

[id='clientdiftechprocessingpapigatewayapicardsv1ReissueDigitalCardResponse']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".client.diftech.processing.papi.gateway.api.cards.v1.ReissueDigitalCardResponse"]
|===
| Response Fields | Source | Logic
| body
a|
----
-
----
a|
[subs="+macros"]
----
xref:clientdiftechprocessingpapigatewayapicardsv1ReissueDigitalCardBody[ReissueDigitalCardBody]
----
| error
a|
----
-
----
a|
[subs="+macros"]
----
xref:clientdiftechprocessingpapigatewayapicardsv1ReissueDigitalCardError[ReissueDigitalCardError]
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/client/diftech/processing/papi/gateway/api/cards/v1/reissue_digital_card.proto[2.1.1 ReissueDigitalCardBody]

[id='clientdiftechprocessingpapigatewayapicardsv1ReissueDigitalCardBody']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".client.diftech.processing.papi.gateway.api.cards.v1.ReissueDigitalCardBody"]
|===
| Response Fields | Source | Logic
| card
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2Card[Card]
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.2 Card]

[id='commondiftechprocessingcaatypesv2Card']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.Card"]
|===
| Response Fields | Source | Logic
| id
a|
----
CreateVirtualCardResponse (card.id)
----
a|
[subs="+macros"]
----
as is
----
| pin
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardPin[CardPin]
----
| type
a|
----
CreateVirtualCardResponse (card.type)
----
a|
[subs="+macros"]
----
CreateVirtualCardResponse(card.form)
----
| number
a|
----
CreateVirtualCardResponse(card.number)
----
a|
[subs="+macros"]
----
last_four_digits
----
| status
a|
----
CreateVirtualCardResponse(card.status)
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardStatus[CardStatus]

----
| balance
a|
----
GetOTBByAccountIdResponse.otb
----
a|
[subs="+macros"]
----
xref:googletypeMoney[Money]
as is
----
| skin_type
a|
----
CreateVirtualCardResponse (card.design)
----
a|
[subs="+macros"]
----
If CORE.design = CORE CARD_DESIGN_CREDITO → set  CARD_SKIN_TYPE_UNSPECIFIED

If CORE.design = CARD_DESIGN_VIAJES → set  CARD_SKIN_TYPE_TRAVEL

If CORE.design = CARD_DESIGN_CUENTA → set  CARD_SKIN_TYPE_DEBIT

If CORE.design = CARD_DESIGN_UNSPECIFIED  set  CARD_SKIN_TYPE_UNSPECIFIED
----
| reissuance
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv1ApplicationByTypes[ApplicationByTypes]
it is virtual card
applications are impossible
----
| restrictions
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardRestrictions[CardRestrictions]
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v1/card_applications.proto[2.1.3 ApplicationByTypes]

[id='commondiftechprocessingcaatypesv1ApplicationByTypes']


=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v1/card_applications.proto[2.1.4 AmbassadorApplication]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v1/datetime_range.proto[2.1.5 DateTimeRange]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v1/card_applications.proto[2.1.6 PostalApplication]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/types/std/v1/timestamp.proto[2.1.7 Timestamp]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.8 CardPin]

[id='commondiftechprocessingcaatypesv2CardPin']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardPin"]
|===
| Response Fields | Source | Logic
| show_pin_data
a|
----
-
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2ShowPinData[ShowPinData]
----
| pin_change_flow
a|
----
CreateVirtualCardResponse (card.processor), feature_toggles (caa_change_pin_available)
----
a|
[subs="+macros"]
----
flow = PIN_CHANGE_FLOW_DISABLED
    when caa_change_pin_available=false

flow = PIN_CHANGE_FLOW_NATIVE
    when caa_change_pin_available=true AND card.processor = PROCESSOR_PHOENIX

flow = PIN_CHANGE_FLOW_WEB_VIEW
    when caa_change_pin_available=true AND card.processor = PROCESSOR_UNSPECIFIED OR PROCESSOR_GALILEO

flow = PIN_CHANGE_FLOW_UNSPECIFIED
    other cases
----
| pin_change_status
a|
----
CreateVirtualCardResponse (card.pin_change_status)
----
a|
[subs="+macros"]
----
status = PIN_CHANGE_STATUS_INITIATED
    when pin_change_status = PIN_CHANGE_STATUS_COMMITTED OR PIN_CHANGE_STATUS_VISITED_POS

status = PIN_CHANGE_STATUS_FAILED
    when pin_change_status = PIN_CHANGE_STATUS_FAILED

all other pin_change_status we ignore pin_change_status is null

----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.9 ShowPinData]

[id='commondiftechprocessingcaatypesv2ShowPinData']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.ShowPinData"]
|===
| Response Fields | Source | Logic
| change_pin_action
a|
----
CreateVirtualCardResponse (card.pin_change_status, card.pin_change_status_time), feature_toggles (caa_change_pin_available)
----
a|
[subs="+macros"]
----
action: SHOW_PIN_CHANGE_PIN_ACTION_DISABLED
    when toggle caa_change_pin_available = false

action: SHOW_PIN_CHANGE_PIN_ACTION_ENABLED_WITH_ACCENT
    when toggle caa_change_pin_available = true
    AND pin_change_status = PIN_CHANGE_STATUS_COMMITTED
    AND pin_change_status_time till Now is less full days than Config.recentChangeDays

action: SHOW_PIN_CHANGE_PIN_ACTION_ENABLED
    when toggle caa_change_pin_available = true
    AND (pin_change_status != PIN_CHANGE_STATUS_COMMITTED
        OR pin_change_status_time till Now is more days than Config.recentChangeDays)

SHOW_PIN_CHANGE_PIN_ACTION_UNSPECIFIED
    other cases
----
| presentation_type
a|
----
CreateVirtualCardResponse (card.show_pin_processor), feature_toggles (caa_show_pin_available)
----
a|
[subs="+macros"]
----
type: SHOW_PIN_PRESENTATION_TYPE_DISABLED
    when toggle caa_show_pin_available=false

type: SHOW_PIN_PRESENTATION_TYPE_TEXT
    when toggle caa_show_pin_available=true AND show_pin_processor = PROCESSOR_PHOENIX

type: SHOW_PIN_PRESENTATION_TYPE_IMAGE
    when toggle caa_show_pin_available=true AND show_pin_processor = PROCESSOR_UNSPECIFIED OR PROCESSOR_GALILEO

type: SHOW_PIN_PRESENTATION_TYPE_UNSPECIFIED
    other cases

----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.10 CardRestrictions]

[id='commondiftechprocessingcaatypesv2CardRestrictions']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardRestrictions"]
|===
| Response Fields | Source | Logic
| is_account_locked
a|
----
GetAccountByIdResponse (restriction.debit_block)
----
a|
[subs="+macros"]
----
debit_block as is
----
| has_spending_limit
a|
----
CreateVirtualCardResponse (cards.limits)
----
a|
[subs="+macros"]
----
if limits is not empty  has_spending_limit = true
----
| atm_withdrawal_enabled
a|
----
CreateVirtualCardResponse (card.cash_withdrawal_enabled)
----
a|
[subs="+macros"]
----
as is
----
| tokenization_available
a|
----
CreateVirtualCardResponse (card.tokenization_enabled)
----
a|
[subs="+macros"]
----
as is
----
| online_purchases_enabled
a|
----
CreateVirtualCardResponse (card.online_payments_enabled)
----
a|
[subs="+macros"]
----
as is
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.11 CardStatus]

[id='commondiftechprocessingcaatypesv2CardStatus']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardStatus"]
|===
| Response Fields | Source | Logic
| type
a|
----
CreateVirtualCardResponse (card.status, card.status_initiator)
----
a|
[subs="+macros"]
----
status = CARD_STATUS_TYPE_ACTIVE
    when card.status = CARD_STATUS_ACTIVE

status = CARD_STATUS_TYPE_FROZEN
    when card.status = CARD_STATUS_FROZEN

status = CARD_STATUS_TYPE_CLOSED
    when card.status = CARD_STATUS_CLOSED

status = CARD_STATUS_TYPE_EXPIRED
    when card.status =  CARD_STATUS_EXPIRED

status = CARD_STATUS_TYPE_BLOCKED
    when
    - card.status =  CARD_STATUS_BLOCKED
    - card.status =  CARD_STATUS_FROZEN AND status_initiator=Antifraud

status = CARD_STATUS_TYPE_UNSPECIFIED
    when card.status in (CARD_STATUS_UNSPECIFIED, CARD_STATUS_NEW, CARD_STATUS_DELIVERED_TO_OFFICE, CARD_STATUS_DELIVERED_TO_USER)

----
| resolve_action
a|
----
CreateVirtualCardResponse (card.status, card.fraud_confirmed)
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardStatusResolveAction[CardStatusResolveAction]
Set if card.status = CARD_STATUS_BLOCKED and fraud_confirmed = false
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.12 CardStatusResolveAction]

[id='commondiftechprocessingcaatypesv2CardStatusResolveAction']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardStatusResolveAction"]
|===
| Response Fields | Source | Logic
| contact_support
a|
----
GetRestrictedTransactionsByCardsResponse (needs_user_confirmation)
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardStatusResolveActionContactSupport[CardStatusResolveActionContactSupport]
Set review_transaction if ANTIFRAUD.RestrictionManager.GetRestrictedTransactionsByCardsResponse.RestrictedTransactionData.needs_user_confirmation = false

----
| review_transaction
a|
----
GetRestrictedTransactionsByCardsResponse (needs_user_confirmation)
----
a|
[subs="+macros"]
----
xref:commondiftechprocessingcaatypesv2CardStatusResolveActionReviewTransaction[CardStatusResolveActionReviewTransaction]
Set review_transaction if ANTIFRAUD needs_user_confirmation = true

----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.13 CardStatusResolveActionContactSupport]

[id='commondiftechprocessingcaatypesv2CardStatusResolveActionContactSupport']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardStatusResolveActionContactSupport"]
|===
| Response Fields | Source | Logic

|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/common/diftech/processing/caa/types/v2/card.proto[2.1.14 CardStatusResolveActionReviewTransaction]

[id='commondiftechprocessingcaatypesv2CardStatusResolveActionReviewTransaction']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".common.diftech.processing.caa.types.v2.CardStatusResolveActionReviewTransaction"]
|===
| Response Fields | Source | Logic
| operation_id
a|
----
GetFeedResponse (operation.id)
----
a|
[subs="+macros"]
----
as is
----
|===

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/google/type/money.proto[2.1.15 Money]

=== link:https://gitlab.diftech.org/common/protos/-/blob/main/proto/client/diftech/processing/papi/gateway/api/cards/v1/reissue_digital_card.proto[2.1.16 ReissueDigitalCardError]

[id='clientdiftechprocessingpapigatewayapicardsv1ReissueDigitalCardError']
[cols="15%,30%,55%",options="header",data-dependency-id=504,data-model=".client.diftech.processing.papi.gateway.api.cards.v1.ReissueDigitalCardError"]
|===
| Response Fields | Source | Logic
| type
a|
----
-
----
a|
[subs="+macros"]
----
-
----
| message
a|
----
-
----
a|
[subs="+macros"]
----
-
----
|===

== 🗂️ Validations

. Сheck that reissue card belongs to the user
if  Req.header.x-plata-user-id != CORE.card.user_id than return an error and break the reissuing process.

. Сheck antifraud block
if card.antifraud_restrictions.fraud_confirmed = true where card.id = card_id than return an error and break the reissuing process.

. Check issued digital card in month (all cards by account_id )
.. count how many cards are issued in the current month to this account
by cards.activate_time(Cards.Virtual.MonthlyLimit for CM form==CARD_FORM_VIRTUAL,
сards in all GW statuses participate in this monthly calculation)
.. If month issued cards count >=  Config.Virtual.MonthlyLimit →
throw error: ERROR_TYPE_MONTHLY_LIMIT_REACHED